server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: phammmquang@gmail.com
    password: ntxdcegihtmbijfz
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true